
// canvasState
export const SET_WORKER = "SET_WORKER";
export const SET_CANVAS_WATERFALL_DELAY = "SET_CANVAS_WATERFALL_DELAY";

//keyboardState
export const CLEAR_NOTES_ARRAY = "CLEAR_NOTES_ARRAY";
export const CLEAR_NOTES_INDICES_ARRAY = "CLEAR_NOTES_INDICES_ARRAY";
export const SET_WHITE_NOTE_WIDTH_SIZE = "SET_WHITE_NOTE_WIDTH_SIZE";
export const SET_NOTE_PRESSED = "SET_NOTE_PRESSED";
export const SET_MOUSE_PRESSED = "SET_MOUSE_PRESSED";
export const SET_NOTE_KEY = "SET_NOTE_KEY";
export const ADD_NOTE = "ADD_NOTE";
export const ADD_NEW_KEY_INDEX = "ADD_NEW_KEY_INDEX";
export const UPDATE_INDEX_KEY = "UPDATE_INDEX_KEY";
export const DELETE_INDEX_KEY = "DELETE_INDEX_KEY";
export const CLEAR_PRESSED_KEYS = "CLEAR_PRESSED_KEYS";

//menuState
export const SET_SHOW_CONFIG = "SET_SHOW_CONFIG"
export const SET_OCTAVES = "SET_OCTAVES";
export const SET_EDIT_KEYS = "SET_EDIT_KEYS";
export const SET_SHOW_KEYS = "SET_SHOW_KEYS";
export const SET_SHOW_NOTES = "SET_SHOW_NOTES";
export const SET_IS_MOUSE_PRESSED = "SET_IS_MOUSE_PRESSED";
export const SET_PLAYING = "SET_PLAYING";
export const SET_WHITE_NOTE_COLOR = "SET_WHITE_NOTE_COLOR";
export const SET_BLACK_NOTE_COLOR = "ET_BLACK_NOTE_COLOR";
export const SET_SUSTAIN = "SET_SUSTAIN";
export const SET_VOLUME = "SET_VOLUME";
export const SET_SPEED = "SET_SPEED";

//playlistState
export const SET_CURRENT_SONG = "SET_CURRENT_SONG";
export const SET_CURRENT_SONG_DURATION = "SET_CURRENT_SONG_DURATION";
export const SET_IS_LOADING = "SET_IS_LOADING";
export const ADD_NEW_RECORDED_SONG = "ADD_NEW_RECORDED_SONG";
export const ADD_TIMER = "ADD_TIMER";
export const CLEAR_TIMERS = "CLEAR_TIMERS";

//recordingState
export const SET_RECORDER = "SET_RECORDER"
export const SET_IS_RECORDING = "SET_IS_RECORDING";
export const SET_START_RECORD_TIME = "SET_START_RECORD_TIME";
export const SET_END_RECORD_TIME = "SET_END_RECORD_TIME";
export const SET_SAVE_RECORDING_DIALOG = "SET_SAVE_RECORDING_DIALOG";
export const ADD_RECORD_MIDI = "ADD_RECORD_MIDI";
export const ADD_RECORD_AUDIO = "ADD_RECORD_AUDIO";
export const ADD_RECORD_MAP = "ADD_RECORD_MAP";
export const CLEAR_RECORD_MIDI = "CLEAR_RECORD_MIDI";
export const CLEAR_RECORD_AUDIO = "CLEAR_RECORD_AUDIO";
export const CALCULATE_DURATION_AND_TIME_MIDI = "CALCULATE_DURATION_AND_TIME_MIDI";

//toneState
export const CREATE_SAMPLER = "CREATE_SAMPLER";